apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: v1
kind: Pod
metadata: 
  name: dev-nginx-pod
  namespace: dev
spec:
  containers:
    - name: c00
      image: nginx:latest
      ports:
        - containerPort: 80
---

#03 == Create a namespace named dev and deploy a POD within it. Name the pod dev-nginx-pod and use the nginx image with the latest tag. Ensure to specify the tag as nginx:latest.
