apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: v1
kind: Pod
metadata: 
  name: dev-nginx-pod
  namespace: dev
spec:
  containers:
    - name: c00
      image: nginx:latest
      ports:
        - containerPort: 80
